### ISSUE TITLE
Implement server-side storage / accounts

### ISSUE THREAD

**Issue by bourgeoisor** [bourgeoisor/xivtodo#13]
Currently, XIV ToDo utilizes [localStorage](https://www.w3schools.com/jsref/prop_win_localstorage.asp) for storing character data. This works, but means that there is no cross-device capabilities (e.g. syncing the same character progress on mobile and on a desktop browser).

A server-side service coupled with storage could be used to enable this (complete with e.g. Discord oAuth).

**Comment by Coggi** [comment]
Hi,

is this being worked on?
It would be very useful for people like me who plays from different PCs :/

Thank you!

**Comment by Kunamatata** [comment]
@bourgeoisor happy to help you with this task if you have any leads or any backend already.

**Comment by bourgeoisor** [comment]
Between Endwalker and work, I haven't had much opportunity to work on this, but it's one of my goal for early 2022!

**Comment by Kunamatata** [comment]
Enjoy endwalker <3 There is no rush!

**Comment by bourgeoisor** [comment]
This is now implemented in https://github.com/bourgeoisor/xivtodo/pull/19 🎉

Announcement Tweet: https://twitter.com/XIVToDo/status/1503906490788237312

**Comment by bourgeoisor** [comment]
Hi @jayna37! I understand your feedback and empathize, but as a sole developer doing this in my free time (and with limited funds -- practically nil) I wouldn't want to put it on me to securely store user credentials. With oauth, that is out of my hands and I don't need to worry about data leaks coming from my side, since XIV ToDo doesn't store or handle any user credentials.

I _could_ consider implementing oauth with other Discord alternatives like Google or Twitter (X), but if I understand your feedback correctly this wouldn't help you, since you'd have to give your phone number (or other information) to _those companies_ just as well.

Re-implementing an "offline" mode (no accounts, data stored locally only) is also very unrealistic for me, given the limited amount of time I can spare on this project.

Do you have any other suggestions?

**Comment by jayna37** [comment]
Thank you for your extensive reply, that means a lot. For me personally indeed Google and X are not services I use or would like to use. But I could imagine that for some users that would already be an improvement that they would enjoy.

Definitely understand that having to store auth credentials yourself is not on the table. Here are some OAuth2 / OpenID Connect providers that I think you could also consider:
* [SimpleLogin](https://simplelogin.io/docs/siwsl/intro/) - a subsidiary of Proton AG (Proton Mail etc.)
* [Twitch](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/) - also gaming-related, belongs to Amazon but doesn’t generally require personal information just to maintain the account
* GitHub and/or GitLab - there‘s some overlap between avid gamers and developers, so these could still be a good fit.

I would also happy to develop, test and make a PR for another service if you are in support of adding it in general.
