### ISSUE TITLE
Blurred items still show hover text

### ISSUE THREAD

**Issue by tasonosenshi** [bourgeoisor/xivtodo#24]
When an item is blurred, it probably shouldn't show hover text either. (mouse doesn't get captured with my screenshots, but it's over the first item in the list)

![image](https://user-images.githubusercontent.com/45836420/163751415-d312d7a1-721b-4eb6-a70b-1161105ac2ba.png)

**Comment by tasonosenshi** [comment]
I'm not sure, but maybe something like `pointer-events: none;` in the css for the blurred text could work?

**Comment by tasonosenshi** [comment]
Probably should add this to the `duty-list-item-blur` class since that's applied to the span containing the title attribute:
https://github.com/bourgeoisor/xivtodo/blob/main/src/components/DutyListItem.vue#L89

**Comment by bourgeoisor** [comment]
Thank you for pointing this out! I've pushed a fix in https://github.com/bourgeoisor/xivtodo/commit/97ebd6f8b678e757753946c2ef7e0baa7e2ae7a4
