### ISSUE TITLE
Not tracking Questlines on relatively new character

### ISSUE THREAD

**Issue by Nivyan** [bourgeoisor/xivtodo#27]
Hey there

I'm unsure if I've made a mistake, so I'm sorry if I'm making a ticket for some misunderstanding on my part.

I just added [this character](https://eu.finalfantasyxiv.com/lodestone/character/29345278/) which successfully added everything but the questlines tab, despite having completed most of the A Realm Reborn MSQ.

**Comment by bourgeoisor** [comment]
It looks like the tribal quests for ARR do unlock _before_ finishing 2.0 (around the level 40s quests), so I've made sure they're always visible now: https://github.com/bourgeoisor/xivtodo/commit/515b62c67026020ac24efe01e01c0179bed0b5aa

The rest of the questlines are 2.x and up though, so they won't show up in the questlines tab until you've cleared the last quest of 2.0! If this is not your first character or you don't particularly care for potential spoilers, you can always show everything through the settings:
![image](https://user-images.githubusercontent.com/3271352/177210234-853f485c-e8da-4c36-93f7-8986f9d5bdfd.png)

I'll close this for now, but do feel free to reopen if a questline should be shown that's not visible for you!
