### ISSUE TITLE
Encounter blurring

### ISSUE THREAD

**Issue by rjb8682** [bourgeoisor/xivtodo#3]
First of all, great site!

Had a quick thought this morning, I think it might be nice for users to have an additional setting that allows them to toggle encounter blurring on based on latest expansion or not. The options would only show if you have something selected under **Content spoilers** that is not 'Show all encounters'.

So maybe the options would be:
- All expansions
- Latest expansion

I'd be happy to make a PR if you're open to it, as well

**Comment by bourgeoisor** [comment]
Is your suggestion that there would essentially be the following 4 options?
- Blur out all story-related encounters 
- Blur out non-completed story-related encounters (all expansions)
- Blur out non-completed story-related encounters (latest expansion only)
- Show all encounters

I am receptive to the suggestion, but I am trying to think of a use case where one would be opened to spoilers of content they haven't cleared _except_ for the latest expansion, given that older expansions should still be considered spoilers regardless of how old they are. Thoughts?

**Comment by rjb8682** [comment]
Yeah, that's a much simpler version and makes a ton more sense.

As for that, I think it's a personal taste. The use case in my head is actually around the time we're in now before Endwalker. I'm caught up on the story, so past dungeons, raids, etc. that I skipped don't hold as much importance for avoiding spoilers. Unsure how popular of a perspective that is with others, though.

**Comment by bourgeoisor** [comment]
The idea with the blur is that I'm only blurring mandatory MSQ content, so if you are indeed caught up to the story there shouldn't be anything else blurred, even if you're missing a lot of optional dungeons, raids, and trials. If that is not what you're experiencing, I would love to take a look at your character!

**Comment by rjb8682** [comment]
Hmmm I just looked again and it's not blurred now. I wonder if it was due to the rate limiting from the other day. I may have just looked at it wrong and didn't process the connection XD

**Comment by bourgeoisor** [comment]
Ah yes, that's a different issue. The Lodestone API was getting rate-limited (and sort of still is but to a lesser extent), so XIV ToDo might've thought that you hadn't cleared some MSQ content even though you had (the API was returning incomplete data from Lodestone).
I am actively working on mitigation for this.

**Comment by rjb8682** [comment]
Yeah, no worries! I'll close the bug as it's not really an issue. Thanks for the explanation!
