### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by jeifour** [bourgeoisor/xivtodo#4]
Would be nice to use the website in French, German and Japanese. Especially all the names of dungeons, trials, etc.

Or if that's too much work, then a setting to your preferred language-version of the Lodestone would already be helpful. I think right now it's always linking to "na.finalfantasyxiv.com/lodestone[...]"

**Comment by bourgeoisor** [comment]
This was in-progress before I announced the project on Reddit (e.g. https://github.com/bourgeoisor/xivtodo/tree/main/src/i18n) but I am changing focus to work on stabilization first. This is in the plans though!

**Comment by bourgeoisor** [comment]
Opened #5, #6 and #7 for the other non-English official languages for XIV.
