### ISSUE TITLE
Missing to complete quest activities

### ISSUE THREAD

**Issue by mra1exei** [bourgeoisor/xivtodo#77]
Greetings.
Tell me, how can I find out what is missing on the site in order to complete the activity in the quests?
on the page https://xivtodo.com/questlines/ I have 3 unfinished quests, although I completed all the quests, information about which is on the wiki or there are unfinished job quests on the site

![quest1](https://github.com/bourgeoisor/xivtodo/assets/11307378/a4ac95ee-8853-4567-a9b5-8751e4940ff4) ![quest2](https://github.com/bourgeoisor/xivtodo/assets/11307378/0654e451-8244-4f9f-8745-b2b094750147)

**Comment by bourgeoisor** [comment]
Hi @mra1exei! As far as I'm aware, these quests don't have any in-game achievements for completion, so I can't automatically track them. Any of these quests with a `(?)` icon you can just click on them and they will be manually marked as cleared!

Let me know if you have any other questions or concerns about this!
