### ISSUE TITLE
Incomplete achievements data sets when site under high load

### ISSUE THREAD

**Issue by bourgeoisor** [bourgeoisor/xivtodo#8]
When under high load, [XIVAPI](https://xivapi.com/) gets rate-limited by Lodestone when fetching live data. They recommend not using that API for lots of concurrent pulls of live Lodestone data. For that purpose, I should move to my own back-end infrastructure instead. I started the work of wrapping [godestone](https://github.com/xivapi/godestone) into a REST API: https://github.com/bourgeoisor/magneton

**Comment by wolfcomp** [comment]
You could use the prebuilt [Google Cloud Functions lib](https://github.com/ffxiv-teamcraft/gcf-lodestone) that is made by Miu and Ay in the XIVAPI discord. That being said, it's if you possibly want a faster result than trying to spin up your own project and what not to wrap godestone for an REST API.

**Comment by bourgeoisor** [comment]
I have functions spun up and a commit almost ready to go, hopefully that helps a lot!
