### ISSUE TITLE
Level 100 Jobs on Profile Page are tightly grouped together

### ISSUE THREAD

**Issue by TyrinH** [bourgeoisor/xivtodo#80]
Hello, 
It was mentioned in the Discord server that the Job levels section of the Profile page needs more spacing when the level for a job is at 100. I replicated this locally and confirmed that the spacing should be greater between each job.

<img width="720" alt="Screen Shot 2024-07-05 at 2 32 03 PM" src="https://github.com/bourgeoisor/xivtodo/assets/11969924/f95899a0-d30c-4fb6-b835-ae41fd2e9c32">

It could be fixed by increasing the margin in the style class here on line 39-44 of `jobLevel.vue` file.
`.job-level {
  float: left;
  margin-right: 10px;
  margin-top: 5px;
  width: 22px;
}`

Could I submit a Pull request to fix this? I'd like to contribute to this project if I am allowed.

**Comment by bourgeoisor** [comment]
Hi @TyrinH, thanks for your enthusiasm! I just saw this--

Unfortunately I had already pushed a quick fix for it: https://github.com/bourgeoisor/xivtodo/commit/8403cd6fae5d166cfa7e0341a156560aa5730d9b

**Comment by TyrinH** [comment]
No worries @bourgeoisor! I'm hopeful there will be other opportunities :)
